accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
#from .views import user_login

urlpatterns = [
#        path('login/', user_login, name="login"),
        path('login/', LoginView.as_view(), name='login'),
        path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
        ]

news_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_app.urls')),
    path('account/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_app/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=News.Status.PUBLISHED)

class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class News(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    image = models.ImageField(upload_to='news/images', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    publish_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ["-publish_time"]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("news_detail_page", args=[self.slug])


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return self.email

templates/crud/news_create.html
{% extends 'news/base.html' %}

{% load static %}

{% block title %} Yangilikni qo'shish {% endblock title %}

{% block content %}
  <h2 class="text-center">Yangilik qo'shish</h2>
  <form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class="btn btn-nifo ml-2">Yangilik qo'shish</button>
  </form>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const titleInput = document.querySelector("#id_title");
      const slugInput = document.querySelector("#id_slug");

      function slugify(text) {
        return text.toString().toLowerCase()
          .replace(/\s+/g, '-')
          .replace(/[^\w\-]+/g, '')
          .replace(/\-\-+/g, '-')
          .replace(/^-+/, '')
          .replace(/-+$/, '');
      }

      titleInput.addEventListener("input", function() {
        const slugText = slugify(titleInput.value);
        slugInput.value = slugText;
      });
    });
  </script>
{% endblock %}

templates/crud/news_delete.html
{% extends 'news/base.html' %}

{% load static %}

{% block title %} {{ news.title }} {% endblock title %}

{% block content %}
  <h2 class="text-center">Joriy yangilikni o'chirish</h2>
  <form method="post">{% csrf_token %}
    <p>{{ news.title | truncatewords:$ }}... sarlavhali yangilikni o'chirmoqchimisiz? </p>
    <button type="submit" class="btn btn-danger ml-2">Tasdiqlayman</button>
  </form>
{% endblock content %}

templates/crud/news_edit.html
{% extend 'news/base.html' %}

{% load static %}

{% block title %} {{ news.title }} {% endblock title %}

{% block content %}
  <h2 class="text-center">Joriy yangilikni tahrirlash</h2>
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-info ml-2">Tahrirlash</button>
  </form>
{% endblock %}